
version: "3.2"
services:

  mongo:
    image: mongo
    container_name: "MyMongoDB"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alikadir
      MONGO_INITDB_ROOT_PASSWORD: 12345

  node-app-server:
    container_name: "MyNodeAppServer"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DATABASE_URL="mongodb://alikadir:12345@MyMongoDB:27017/?appname=myNodeExpressApplication" # connect via container name in docker-compose
    depends_on:
      - mongo

